// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MapOnly","status":true,"description":"","parameters":{}},
{"name":"WASD","status":true,"description":"","parameters":{}},
{"name":"NameTag","status":true,"description":"","parameters":{}},
{"name":"MsgVoiceFade","status":true,"description":"","parameters":{}},
{"name":"HideTouchUI","status":true,"description":"","parameters":{}},
{"name":"Cat","status":true,"description":"Play random cat SE when interacting with cat events (Action Button).","parameters":{"seList":"[\"cat1\",\"cat2\",\"cat3\",\"cat4\"]","volume":"90","pitch":"100","pan":"0","namePattern":"^Cat$"}}
];
